# Generated by Django 5.2.3 on 2026-06-18 04:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('species', models.CharField(choices=[('dog', 'Perro'), ('cat', 'Gato'), ('other', 'Otro')], max_length=20)),
                ('breed', models.CharField(blank=True, max_length=120)),
                ('sex', models.CharField(choices=[('male', 'Macho'), ('female', 'Hembra'), ('unknown', 'Desconocido')], default='unknown', max_length=20)),
                ('size', models.CharField(choices=[('small', 'Pequeno'), ('medium', 'Mediano'), ('large', 'Grande')], default='medium', max_length=20)),
                ('approximate_age', models.CharField(blank=True, max_length=80)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('color', models.CharField(blank=True, max_length=120)),
                ('intake_date', models.DateField(default=django.utils.timezone.now)),
                ('intake_reason', models.CharField(blank=True, max_length=120)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('intake', 'Ingresado'), ('observation', 'En observacion'), ('treatment', 'En tratamiento'), ('available', 'Disponible'), ('adoption_process', 'En proceso de adopcion'), ('adopted', 'Adoptado'), ('deceased', 'Fallecido'), ('lost', 'Perdido')], default='intake', max_length=30)),
                ('behavior_notes', models.TextField(blank=True)),
                ('public_description', models.TextField(blank=True)),
                ('personality_tags', models.CharField(blank=True, max_length=255)),
                ('vaccinated', models.BooleanField(default=False)),
                ('sterilized', models.BooleanField(default=False)),
                ('dewormed', models.BooleanField(default=False)),
                ('adoption_ready', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('photo', models.ImageField(blank=True, upload_to='animals/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('category', models.CharField(choices=[('food', 'Alimentos'), ('medicine', 'Medicamentos'), ('cleaning', 'Limpieza'), ('other', 'Otros')], max_length=30)),
                ('unit', models.CharField(max_length=40)),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('minimum_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Adopter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160)),
                ('document', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('housing_type', models.CharField(blank=True, max_length=80)),
                ('owns_or_rents', models.CharField(blank=True, max_length=80)),
                ('has_pets', models.BooleanField(default=False)),
                ('experience', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adopter_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='AdoptionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('review', 'En revision'), ('interview', 'Entrevista'), ('home_visit', 'Visita domiciliaria'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('formalized', 'Formalizada'), ('follow_up', 'Seguimiento')], default='pending', max_length=30)),
                ('motivation', models.TextField()),
                ('official_adoption_date', models.DateField(blank=True, null=True)),
                ('follow_up_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adopter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='shelter.adopter')),
                ('shelter_responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adoption_applications', to='shelter.animal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Entrada'), ('out', 'Salida')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='shelter.inventoryitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('consultation', 'Consulta general'), ('vaccine', 'Vacunacion'), ('deworming', 'Desparasitacion'), ('treatment', 'Tratamiento'), ('surgery', 'Cirugia')], max_length=30)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('diagnosis', models.CharField(max_length=255)),
                ('medication', models.CharField(blank=True, max_length=120)),
                ('dosage', models.CharField(blank=True, max_length=120)),
                ('health_status', models.CharField(choices=[('healthy', 'Saludable'), ('treatment', 'En tratamiento'), ('recovery', 'En recuperacion'), ('critical', 'Critico'), ('not_ready', 'No apto para adopcion'), ('ready', 'Apto para adopcion')], default='healthy', max_length=30)),
                ('next_event', models.CharField(blank=True, max_length=160)),
                ('next_event_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='shelter.animal')),
                ('veterinarian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('volunteer', 'Voluntario'), ('vet', 'Veterinario'), ('adopter', 'Adoptante')], default='adopter', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('is_active_staff', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
