# Generated by Django 5.2.3 on 2026-06-19 21:12

import django.db.models.deletion
import shelter.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=shelter.models.shelter_code, editable=False, max_length=12, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('organization_document', models.CharField(blank=True, max_length=80)),
                ('contact_name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='adopter',
            name='document_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='adopter',
            name='identity_document',
            field=models.FileField(blank=True, upload_to='adopter-documents/'),
        ),
        migrations.AlterField(
            model_name='adopter',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shelter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='shelter.shelter'),
        ),
    ]
