# Generated by Django 5.2.3 on 2026-06-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0002_shelter_adopter_document_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='country',
            field=models.CharField(default='CO', max_length=2),
        ),
        migrations.AddField(
            model_name='animal',
            name='region',
            field=models.CharField(default='Bogota D.C.', max_length=80),
        ),
    ]
