# Generated by Django 5.2.3 on 2026-07-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0006_userprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='currency',
            field=models.CharField(default='COP', max_length=3),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='stock_status_override',
            field=models.CharField(blank=True, choices=[('', 'Automatico'), ('ok', 'Optimo'), ('low', 'Bajo'), ('critical', 'Critico')], max_length=20),
        ),
        migrations.AddField(
            model_name='shelter',
            name='country',
            field=models.CharField(default='CO', max_length=2),
        ),
        migrations.AddField(
            model_name='shelter',
            name='region',
            field=models.CharField(default='Bogota D.C.', max_length=80),
        ),
    ]
